rvm: true
builds:
  build_1:
    environment:
      DATABASE_URL: sqlite3://db/home/build/project/spec/dummy/db/test.sqlite3
    name: SQLite
    script:
      - cd spec/dummy && RAILS_ENV=test bundle exec rake db:drop db:schema:load
      - bundle exec rspec
  build_2:
    environment:
      DATABASE_URL: mysql2://awesome_counter_cache:password@mariadb:3306/awesome_counter_cache_test
    name: MariaDB
    script:
      - cd spec/dummy && RAILS_ENV=test bundle exec rake db:drop db:schema:load
      - bundle exec rspec
  build_3:
    environment:
      DATABASE_URL: postgresql://awesome_counter_cache:password@postgres:5432/awesome_counter_cache_test
    name: Postgres
    script:
      - cd spec/dummy && RAILS_ENV=test bundle exec rake db:drop db:schema:load
      - bundle exec rspec
  linters:
    name: Linters
    script:
      - cd spec/dummy && RAILS_ENV=test bundle exec rake db:drop db:schema:load
      - bundle exec rubocop
services:
  mariadb:
    image: "mariadb:10.8.6"
    environment:
      MYSQL_DATABASE: awesome_counter_cache_test
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: awesome_counter_cache
      MYSQL_PASSWORD: password
    expose:
      - 3306
    restart_policy: on-failure
  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_DB: awesome_counter_cache_test
      POSTGRES_USER: awesome_counter_cache
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    restart_policy: on-failure
