<%
  database = URI(ENV.fetch("DATABASE_URL"))
  adapter = database.scheme

  args = {
    adapter: adapter,
    pool: 5,
    timeout: 5000
  }

  if adapter == "mysql2" || adapter == "postgres"
    args[:username] = database.user
    args[:password] = database.password
    args[:host] = database.host
    args[:port] = database.port
    args[:database] = "awesome_counter_cache_test"
  end

  if adapter == "mysql2"
    args[:encoding] = "utf8mb4"
  elsif adapter == "sqlite3"
    args[:database] = database.path
  end
%>
test:
  <% args.each do |key, value| %>
  <%= key %>: <%= value %>
  <% end %>
